### ISSUE TITLE
Client only detects one experiment option in some cases

### ISSUE THREAD

**Issue by dvdsgl** [quicktype/autotune#45]
![image](https://user-images.githubusercontent.com/108197/41891107-b23a7564-78c7-11e8-8970-321db9f0498c.png)

**Comment by schani** [comment]
Still happens

![image](https://user-images.githubusercontent.com/61363/41938077-ea5bb780-7946-11e8-9817-02d01c07ae83.png)

**Comment by dvdsgl** [comment]
Yes, I see it.
