### ISSUE TITLE
Show meaningful message when results are not available yet

### ISSUE THREAD

**Issue by philals** [quicktype/autotune#49]
Hi. This service looks good. Interested to see where it goes.

I have wired it into my app. I can see the results being sent:

![image](https://user-images.githubusercontent.com/8849355/42414810-1b9a1446-8292-11e8-8ac6-4e39984535a9.png)

However `tune ls 1a60c50e-xxx-c6a260848e1f` does not return any results. Anything from your side?

**Comment by schani** [comment]
@philals Thanks for giving us a try!  Results take a while to accumulate.  How long ago did you start your first experiments?

**Comment by philals** [comment]
Thanks @schani 

It was maybe 30 mins ago, probably more. It's just me testing locally. Do results need time, or lots of data to accumulate? 

I'll leave it a while longer, and try later today.

**Comment by dvdsgl** [comment]
@philals, how did you find our project btw? Thanks again for trying it out!

**Comment by schani** [comment]
@philals It should show something by now.

Statistics on experiments are accumulated periodically in batches, so it just takes a while for numbers to show up.

**Comment by philals** [comment]
@schani Working, well now thanks! I'm getting results.

@dvdsgl  I'm trying to figure out a nice way to do A/B testing on our React SPA. I have wired up react-ab-test (passes event to GA) into it. I'll be running an experiment soon. Reading the issues on that repo lead me here. 

I'm quite interested in the idea of letting the computers figure out the optimal configuration for our site.

**Comment by schani** [comment]
I always commit as myself ;-)

Thank you so much for the PR!
